---
title: "Survival Analysis"
output: pdf_document
params:
  n: NA
  surv.data: NA
  cox: NA
  main: NA
  xlab: NA
  ylab: NA
  lwd: NA
  cex.axis: NA
  cex.lab: NA
  cex.main: NA
  cex.legend: NA
  confidence_interval: NA
  mark.time: NA
  log: NA
  colors: NA
  linetype: NA
  margin.size: NA
---
Write. 

<!-- Plot -->

```{r, echo = FALSE}
    # change this is still from shiny...give all values in params
    # setting the plot titles and styles
    # change here settings here
    main = params$main
    xlab = params$xlab
    ylab = params$ylab
    lwd = params$lwd
    cex.axis = params$cex.axis
    cex.lab = params$cex.lab
    cex.main = params$cex.main
    cex.legend = params$cex.legend
    confidence_interval = params$confidence_interval
    mark.time = params$mark.time
    log = params$log
    colors = params$colors
    linetype = params$linetype
    par(mar = rep(params$margin.size, 4))

    plot(params$surv.data, conf.int = confidence_interval, col = colors$color, lty = linetype$lty, lwd = lwd, mark.time = mark.time,
        xlab = xlab, ylab = ylab, main = main, log = log,
        cex.axis = cex.axis, cex.lab= cex.lab, cex.main = cex.main)
    if(length(colors$color.legend) > 1){
      legend('topright', legend = colors$category, col = colors$color.legend, cex = cex.legend, title = colors$legend_name, lty = 1, bty = 'n')
    }
    if(length(linetype$linetype.legend) > 1){
      legend('bottomleft', legend = linetype$category, lty = linetype$linetype.legend, cex = cex.legend, title = linetype$legend_name, col = colors$color.legend[1], bty = 'n')
    }

```


<!-- stats output -->

```{r, echo = FALSE}
    print(summary(params$cox))
```